# run: conda env create --file environment.yml
name: scp-infer
channels:
- bioconda
dependencies:
- python>=3.5
- anaconda
- pip
- numpy
- pandas
- scanpy
- torch   # necessary for DCDI
- arboreto==0.1.5  # for GRNBoost2 implementation
- pip:
  - gies
  - matplotlib